name: FlyFeather
version: 1.0
main: com.stormai.plugin.Main
api-version: 1.20
authors: [ Stormai ]
description: Gives players a feather on join that allows 10 seconds of flight with a 5 second cooldown

commands:
  flyfeather:
    description: Reloads the plugin configuration
    usage: /flyfeather reload

permissions:
  flyfeather.use:
    description: Allows use of the Fly Feather
    default: true